#!/usr/bin/env python3
"""Player teams for 2026-05-25 slate (53 HR props)."""
PLAYER_TEAMS = {
    "Michael Busch (L)": "CHC",
    "Michael Conforto (L)": "CHC",
    "Brandon Lowe (L)": "PIT",
    "Jonathan Aranda (L)": "TB",
    "Yandy Diaz (R)": "BAL",
    "Weston Wilson (R)": "BAL",
    "Pete Alonso (R)": "BAL",
    "Jake Bauers (L)": "STL",
    "William Contreras (R)": "MIL",
    "Andrew Vaughn (R)": "STL",
    "Ivan Herrera (R)": "MIL",
    "Jordan Walker (R)": "MIL",
    "Alec Burleson (L)": "STL",
    "Colson Montgomery (L)": "CWS",
    "Miguel Vargas (R)": "CWS",
    "Jarred Kelenic (L)": "MIN",
    "Byron Buxton (R)": "MIN",
    "Ben Rice (L)": "NYY",
    "Aaron Judge (R)": "NYY",
    "Bobby Witt Jr. (R)": "KC",
    "Jac Caglianone (L)": "KC",
    "Bo Bichette (R)": "CIN",
    "Elly De La Cruz (S)": "CIN",
    "Nathaniel Lowe (L)": "CIN",
    "Corbin Carroll (L)": "ARI",
    "Ketel Marte (S)": "ARI",
    "Willy Adames (R)": "SF",
    "Rafael Devers (L)": "SF",
    "Harrison Bader (R)": "SF",
    "James Wood (L)": "WSH",
    "Daylen Lile (L)": "WSH",
    "Curtis Mead (R)": "WSH",
    "Kyle Manzardo (L)": "CLE",
    "Patrick Bailey (S)": "WSH",
    "Kyle Schwarber (L)": "PHI",
    "Nick Castellanos (R)": "PHI",
    "Manny Machado (R)": "SD",
    "Yordan Alvarez (L)": "HOU",
    "Christian Walker (R)": "TEX",
    "Brandon Nimmo (L)": "HOU",
    "Josh Jung (R)": "TEX",
    "Ezequiel Duran (R)": "TEX",
    "Owen Caissie (L)": "MIA",
    "Kyle Stowers (L)": "MIA",
    "Jesus Sanchez (L)": "MIA",
    "George Springer (R)": "TOR",
    "Daulton Varsho (L)": "TOR",
    "Max Muncy (L)": "LAD",
    "Freddie Freeman (L)": "LAD",
    "Brent Rooker (R)": "SEA",
    "Nick Kurtz (L)": "ATH",
    "Luke Raley (L)": "SEA",
    "Mitch Garver (R)": "SEA",
}

FAVS = [
    "Brandon Lowe (L)",
    "Michael Conforto (L)",
    "Pete Alonso (R)",
    "Ivan Herrera (R)",
    "Jordan Walker (R)",
    "Miguel Vargas (R)",
    "Jac Caglianone (L)",
    "Kyle Schwarber (L)",
]
