(function(){
 'use strict';
 const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const markets={pts:'Points',reb:'Rebounds',ast:'Assists',threem:'Threes',pra:'Points + rebounds + assists',pr:'Points + rebounds',pa:'Points + assists',ra:'Rebounds + assists',stl:'Steals',blk:'Blocks',stocks:'Steals + blocks',tov:'Turnovers',dd:'Double double',td:'Triple double'};
 function card(p,date){
  const link='index.html?date='+encodeURIComponent(date||'')+'&game='+encodeURIComponent(p.game_id||'')+'&player='+encodeURIComponent(p.player_id||'');
  const result={hit:'Hit',miss:'Miss',void:'Void',pending:'Pending'}[p.result]||'Pending';
  const pick = !['hit','miss','void'].includes(p.result) ? ' data-ledger-pick="'+esc(JSON.stringify({sport:'NBA',name:p.player,market:(p.side==='under'?'Under':'Over')+' '+p.line+' '+(markets[p.market]||p.market),event:p.matchup||'',date:p.kickoff||date||''}))+'"' : '';
  return '<article class="sheet-top-card"'+pick+'><div class="sheet-top-card__head"><a class="sheet-top-card__name" href="'+esc(link)+'">'+esc(p.player)+'</a><span class="chip">'+result+'</span></div><span class="sheet-top-card__meta">'+esc(p.matchup||'')+(p.kickoff?' · '+esc(new Date(p.kickoff).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})):'')+'</span><div class="ledger-card-line">'+esc(p.side==='under'?'Under':'Over')+' '+esc(p.line)+' <span>'+esc(markets[p.market]||p.market)+'</span></div>'+(p.odds?'<span class="sheet-m"><b>'+esc(p.odds)+'</b> '+esc(p.book||'Listed price')+'</span>':'')+(p.note?'<p class="sheet-why">'+esc(p.note)+'</p>':'')+'<div class="ledger-card-links"><a class="sheet-back" href="'+esc(link)+'">Player research →</a></div></article>';
 }
 $('ledger-theme').onclick=()=>{const light=document.documentElement.classList.toggle('theme-light');try{localStorage.setItem('worstpickz-theme',light?'light':'dark');}catch(e){}};
 (async()=>{try{const response=await fetch('../data/nba-prop-ledger.json',{cache:'no-store'});if(!response.ok)throw Error('Unable to load the ledger.');const data=await response.json();const picks=(data.picks||[]).filter(p=>p.player&&p.market&&Number.isFinite(p.line)&&['over','under'].includes(p.side));const open=picks.filter(p=>!['hit','miss','void'].includes(p.result)),settled=picks.filter(p=>['hit','miss','void'].includes(p.result));$('ledger-date').textContent=data.date?new Date(data.date+'T12:00:00').toLocaleDateString([],{weekday:'short',month:'short',day:'numeric'}):'';$('ledger-date').hidden=!data.date;$('ledger-status').textContent=data.updated?'Updated '+new Date(data.updated).toLocaleString():'No picks posted yet';$('ledger-counts').innerHTML='<span class="sheet-count">'+picks.length+' selected '+(picks.length===1?'prop':'props')+'</span>';$('ledger-empty').hidden=picks.length>0;$('ledger-picks').innerHTML=open.map(p=>card(p,data.date)).join('');$('ledger-results-section').hidden=!settled.length;$('ledger-results').innerHTML=settled.map(p=>card(p,data.date)).join('');}catch(e){$('ledger-status').textContent=e.message;}})();
})();
